### ISSUE TITLE
Perfect! When do you update next version? 

### ISSUE THREAD

**Issue by mierlaile** [practicalAI/practicalAI#136]
Looking forward to the next release. Hahaha, thank you very much.

**Comment by GokuMohandas** [comment]
Hey @mierlaile , the next version will have videos and will be much more interactive. I'll be releasing the first video in another week and a half. You can stay updated at https://practicalai.me

**Comment by zhouxincheng** [comment]
> Hey @mierlaile , the next version will have videos and will be much more interactive. I'll be releasing the first video in another week and a half. You can stay updated at https://practicalai.me

hello, I can't find the video or the next section?  So looking forward to the next section
