### ISSUE TITLE
Homepage Not Loading

### ISSUE THREAD

**Issue by loganwedwards** [practicalAI/practicalAI#168]
[Homepage](https://practicalai.me/) does not seem to work.

**Comment by GokuMohandas** [comment]
hey @loganwedwards , we're only available through this GitHub page for now.

**Comment by loganwedwards** [comment]
Got it. It might be useful to update the top of the Github page since it has a link to `https://practicalai.me`. It is confusing for users. Thanks for the great repo!

**Comment by GokuMohandas** [comment]
oh good catch @loganwedwards! and thank you! I actually just released something related a few hours ago which you might be interested in:

https://madewithml.com - it’s a platform to share what you’ve made with ML. You can use it to:
1. Share and discover ML projects
2. Create your profile to showcase your projects for getting a job

The hardest part of getting an ML job is getting the interview itself so I’m working directly with hiring managers from top tech companies (FAANG+) and niche startups who will look at candidates’ projects to decide who to interview and talk about them during the on-site interviews. They realize that projects are a much more meaningful signal compared to college, GPA or testing you on trivial coding puzzles. I’ve written a small blog post about it here:

https://medium.com/@madewithml/7f509ecf2d57?source=friends_link&sk=ace961d53c9f3cf3089e081c0c4ee69c

Let me know what you think and feel free to share it within your networks! It will always be 100% free.
