### ISSUE TITLE
Foundations --> Embeddings

### ISSUE THREAD

**Issue by gitgithan** [practicalAI/practicalAI#203]
1. Typo under Model section: `3. We'll apply convolution via filters (filter_size, vocab_size, num_filters)` should be `embedding_dim` to replace `vocab_size`?
2. Typo under Experiments: `first have to decice`
3. Typo under Interpretability `padding our inputs before convolution to result is outputs` `is` should be `in` 
4. Could there be a general explanation of moving models/data across devices? My current understanding is that they have to be both on the same place (cpu/gpu). If on gpu, just stay on gpu through the whole train/eval/predict session. I couldn't understand why under Inference `device = torch.device("cpu")` moves things back to cpu.
5. `interpretable_trainer.predict_step(dataloader)` breaks with `AttributeError: 'list' object has no attribute 'dim'`. The precise step is `F.softmax(z)`, where for interpretable_model, z is a list of 3 items and it was trying to softmax a list instead of a tensor.

**Comment by JellenRoberts** [comment]
Hi,

I have been part of this thread and have no idea how to end these emails.

Any idea?

Thanks!
